exclude = [
    "agenthub/monologue_agent/regression/",
]

[lint]
select = [
    "B"
]

ignore = [
    "E501",
    "B009",
    "B010",
    "B003",
    "B020"
]

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[format]
quote-style = "single"
